jjeankim/jogeu-market-api

src/app.ts, src/controllers/brandController.ts, src/controllers/productController.ts, src/routes/brandRouter.ts, src/routes/productRouter.ts
Feat : 상품 생성, 조회, 상세조회 기능구현
- 브랜드 생성, 조회 기능과 상품 생성, 조회, 상세조회 기능 구현 완료 
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Feat : 브랜드 생성, 조회 기능 구현

src/controllers/brandController.ts, src/controllers/productController.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Fix : 프리즈마 전역 관리로 변경

prisma/migrations/20250725063410_init/migration.sql, src/app.ts, src/controllers/authController.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Fix : 데이터베이스 다시 생성

src/controllers/productReviewController.ts, src/routes/productReviewRouter.ts
---
---
- 리뷰 수정 및 삭제 엔드포인트 수정 : 기존에 "/api/reviews/id" =>"/api/products/:id/reviews"
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> 리뷰 수정 및 삭제 api 구현

src/constants/errorMessage.ts, src/constants/successMessage.ts, src/controllers/addressController.ts, src/controllers/authController.ts, src/controllers/brandController.ts, src/controllers/cartController.ts, src/controllers/couponController.ts, src/controllers/orderController.ts, src/controllers/productController.ts, src/controllers/productReviewController.ts, src/controllers/sampleController.ts, src/controllers/userController.ts, src/controllers/wishlistController.ts
- constants 폴더에 에러 및 성공 메세지를 작성
---
---
- constants 폴더에 에러 및 성공 메세지를 작성하여 유지보수와 재사용성을 확보
---
- 한꺼번에 작업해서 수정이 필요한 부분이 있을 것 같습니다. 작업 중 발견하시면 수정 부탁드려요!
=> Fix: 에러 메세지 재사용

.gitignore, package-lock.json, package.json, prisma/migrations/20250730024624_/migration.sql, prisma/schema.prisma, src/app.ts, src/constants/errorMessage.ts, src/controllers/authController.ts, src/controllers/productController.ts, src/controllers/productReviewController.ts, src/middleware/upload.ts, src/routes/authRouter.ts, src/routes/productReviewRouter.ts, src/routes/productRouter.ts, src/upload/middleware.ts, src/upload/storage.ts
- 이미지 업로드 기능 구현
- refreshToken api 구현
---
---
- 리뷰 사진(옵셔널) 업로드 기능 
- 상품 썸네일 업로드 기능
- refreshToken api 구현하여 accessToken 만료 시 재 발급 기능
---
- 현재는 로컬에 저장되도록 구현하였고, 추후 애저와 연동하면 스토리지만 변경하면 될 것 같습니다!
- 프로덕트 모델 변경으로 pull 받으신 후 `npx prisma migrate dev` 부탁드립니다.
=> 리뷰 사진 및 상품 썸네일 업로드 기능 구현

src/controllers/authController.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Fix : 유저 아이디도 로컬스토리지에 저장

src/app.ts, src/controllers/cartController.ts, src/controllers/couponController.ts, src/lib/seed.ts, src/routes/cartRouter.ts
Fix : 제품 코드 규칙 정의 후 데이터 수정
- seed 파일로 샘플 데이터들 모두 넣어놨습니다.
- 제품코드 규칙은 노션에 정리해놨음 
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> fix:  쿠폰 에러 수정

src/controllers/orderController.ts, src/lib/seed.ts
---
---
- 주문 관련 된 페이지에서 필요한 api 수정 작업
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> fix : 주문 생성 로직 개선: 주문 요청 데이터 구조 변경, 주소 처리 로직 추가, 주문 상태 및 장바구니 비우기 로직 수정

prisma/schema.prisma
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> fix : 데베 수정

package.json, prisma/schema.prisma, src/controllers/productController.ts, src/lib/seedIsPick.ts
---
---
- Product isPick 컬럼 추가 , isPick seed로 50% 확률 bool값 부여 
- 추가 사유 : 추후 관리자 페이지 확장 가능성 및 Product 받을때  랜딩 상단 nav Pick 에서 활용
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> fix : Product 모델 변경(isPick 컬럼 추가)

prisma/migrations/20250806065451_add_is_pick_field/migration.sql
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> fix: 프로덕트 모델에 isPick 마그레이션 변동이력 추가

prisma/schema.prisma, src/controllers/productReviewController.ts, src/routes/productReviewRouter.ts
- 리뷰 업데이트(수정) 컨트롤러 로직 수정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
- 프론트 처리를 위해 수정했습니다.
- db pull 작업을 하면 db 기준으로 모델이 생성되어 주석이 사라지는 것 같아요.
=> 리뷰 업데이트 컨트롤러 로직 수정

prisma/migrations/20250808050644_w/migration.sql, prisma/schema.prisma, src/app.ts, src/controllers/couponController.ts, src/controllers/productController.ts, src/routes/productRouter.ts
- 기존에 쿠폰 아이디 받아왔는데 그거 말고 유저쿠폰 테이블의 아이디를 받아오도록 
---
---
- 쿠폰 로직 수정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> fix: 사용자가 사용하지 않은 쿠폰만 조회하도록 조건 추가

package.json, src/app.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: generate 후 build

dist/app.js, src/app.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: build test

dist/app.js, package.json, src/app.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> build test

.github/workflows/deploy.yml
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: test build

dist/app.js, src/app.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: app.ts 주석 제거

dist/controllers/authController.js, src/controllers/authController.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: cookie 설정

package-lock.json, package.json, src/app.ts
- hemet & compression 적용
---
---
- helmet 
- X-XXS-Protection: 교차 사이트 스크립팅(XXS) 공격 방어
- Content-Security-Policy : 악성 스크립트 주입을 막기 위해 브라우저가 신뢰하는 소스에서만 콘텐츠 로드
- Hide Powerd-By : X-Powerd-By 헤더를 제거하여 서버가 Express로 구축되었다는 정보 숨김
- Strict-Transport-Security : HTTPS를 사용하도록 강제하여 중간자 공격 방어
- compression : 성능 향상을 위한 미들웨어
- 클라이언트에게 응답을 보내기 전에 데이터를 압축하여 웹 애플리케이션의 성능을 향상시키는 미들웨어  
---
- 개인적으로 그냥 한번 사용해보고 싶어서 설치해씀다
=> helmet & compression 적용

.github/workflows/deploy.yml
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> yml 수정 후 배포

.github/workflows/deploy.yml
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> deploy error

.github/workflows/deploy.yml
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> azure deploy error

README.md
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> 프론트 cors 추가

src/app.ts, src/controllers/authController.ts, src/routes/oauthRouter.ts, src/types/userType.ts, src/utils/token.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Feat: 소셜 로그인 기능 구현

src/controllers/authController.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: 로그아웃 쿠키 로직 수정

src/app.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Chore: proxy 설정 추가

src/app.ts
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
=> Fix: oauth라우터 위치 변경
